### PR TITLE
Frontend updates

### PR DESCRIPTION
**Pull request by samjett247**
Just some cosmetic stuff, mainly with y-ranges for data and adding a temporary fix for some of our backend scraping stuff. We can talk about it later if you want.

### CODE REVIEW

**Comment by schuermannator** [comment]
What’s you end up doing for Y-axis? Sorry on mobile rn

**Comment by samjett247** [comment]
> What’s you end up doing for Y-axis? Sorry on mobile rn

Lol I didnt make that clear. Y axis will be bounded by the nearest integers on each side (eg for ratings [3.1, 3.6, 4.5, 4.3] range would be 3-5). I made that consistent across instructor/course ratings, and consistent on the individual questions as well. The 1-5 yaxes just looked really bad for courses where the variation is O(0.01) - you couldnt tell that there were any differences.

**Comment by samjett247** [comment]
@schuermannator review at your leisure - meant to mention this

**Comment by schuermannator** [comment]
LGTM, tested and did some cleanup/package updates.

**Review by zachschuermann — APPROVED** [review]
LGTM

**Pull request merged**
